Fix MailChimp Test Credentials
workarea-commerce/workarea-mailchimp pull request #3
Opened 2019-10-08 15:48 UTC by tubbo

Update the MailChimp API Key to properly pass the client-side validation
that prevents `Gibbon` from making the calls needed in the tests for
MailChimp. Previously, this was a scrubbed credential and was one
character, which apparently doesn't fly for MailChimp and it caused the
client to block sending out requests, which was the reason behind the
tests failing. The API Key has been regenerated with a
`SecureRandom.hex` string and properly base64-encoded into the VCR
cassettes, which allow the tests to pass now.

MAILCHIMP-1

2019-10-08 20:53 UTC, tubbo commented
still having trouble with CI, which I can only imagine in an issue with Elasticsearch...

2019-10-09 13:06 UTC, bencrouse approved these changes
Your changes seem fine, but those build failures 😢 

Not seeing them other places, but I also doubt it's from these changes. I'm going to merge anyways.

2019-10-09 13:08 UTC, bencrouse requested changes
Actually, can you clean up the commit around Sprockets? No reason to put that in the changelog.

2019-10-10 13:34 UTC, bencrouse approved these changes

2019-10-10 13:34 UTC, merged